/**
 * taskPlanner.ts
 * LLM-based task decomposition.
 *
 * For complex multi-step requests, asks the LLM to break the task into
 * ordered steps (one per line: "category: instruction").
 * Each step then executes with minimal, focused context.
 *
 * ponytail: no graph, no state machine, no enumerated noun lists.
 * Just one small planning call + a simple line parser.
 */

import { api, AppConfig, ChatMessage } from "../../lib/api";

export interface TaskStep {
  id: string;
  label: string;
  category: string;
  /** Natural language instruction for this step */
  prompt: string;
  status: "pending" | "running" | "done" | "error";
  result?: string;
}

export interface TaskPlan {
  originalRequest: string;
  steps: TaskStep[];
  /** Content generated by earlier steps, keyed by content type (haiku, quote, etc.) */
  generatedContent: Record<string, string>;
}

// ---- Planning prompt ----

const PLANNING_SYSTEM = `Break the user's request into steps. Output ONE LINE per step:
CATEGORY: instruction

Categories:
- generation: write/create/compose/generate any content
- whatsapp: send a WhatsApp message to someone
- discord: set Discord status or activity
- email: send an email
- apps: open or launch an application

If only one step is needed, output: SIMPLE

---
Example:
User: Write a haiku about rust and message it to John on WhatsApp. Then set Discord to dnd with activity Debugging.
generation: Write a haiku about how hard it is to write Rust code
whatsapp: Send the haiku to John on WhatsApp
discord: Set Discord status to dnd with activity Debugging
---
Example:
User: Open Chrome and also set my Discord status to idle.
apps: Open Chrome
discord: Set Discord status to idle
---
Example:
User: What time is it?
SIMPLE
---
Now output the steps for the user's request below. Only output step lines or SIMPLE, nothing else.`;

// ---- Pre-filter ----
// Avoids the planning LLM call for obviously simple single-step requests.

const CONJUNCTIONS = /\b(and then|and also|then|also|after that|afterwards|and set|and send|and message|and email|and open|and launch|once you have|once done)\b/i;
const ACTION_WORDS = /\b(write|create|generate|compose|message|send|set|email|open|launch|discord|whatsapp)\b/i;

/**
 * Quick heuristic: does this request look like it needs multiple steps?
 * Only returns true if there's a conjunction AND at least one action keyword.
 * Avoids planning LLM calls for simple queries.
 */
export function mightBeMultiStep(text: string): boolean {
  return CONJUNCTIONS.test(text) && ACTION_WORDS.test(text);
}

// ---- Main entry ----

let _n = 0;
const nextId = () => `s${++_n}`;

/**
 * Ask the LLM to decompose a multi-step request.
 * Returns null if the LLM says it's a single step.
 */
export async function decomposeTask(
  userRequest: string,
  config: AppConfig,
): Promise<TaskPlan | null> {
  const messages: ChatMessage[] = [
    { role: "system", content: PLANNING_SYSTEM },
    { role: "user", content: userRequest },
  ];

  const response = await callLLM(config.selected_model, messages);
  return parsePlanResponse(response, userRequest);
}

// ---- Parsing ----

const CATEGORY_RE = /^(generation|whatsapp|discord|email|apps):\s*(.+)$/i;

function parsePlanResponse(response: string, originalRequest: string): TaskPlan | null {
  const steps: TaskStep[] = [];

  for (const raw of response.split("\n")) {
    const line = raw.trim();
    // Skip blank lines, SIMPLE, and example separators
    if (!line || /^SIMPLE\b/i.test(line) || /^[-=]{2,}/.test(line)) continue;
    const m = line.match(CATEGORY_RE);
    if (!m) continue; // skip lines without a valid CATEGORY: prefix

    const category = m[1].toLowerCase();
    const instruction = m[2].trim();
    if (!instruction) continue;

    steps.push({
      id: nextId(),
      label: makeLabel(category, instruction),
      category,
      prompt: instruction,
      status: "pending",
    });
  }

  // Only decompose if we found 2 or more distinct steps
  if (steps.length <= 1) return null;

  return { originalRequest, steps, generatedContent: {} };
}

function makeLabel(category: string, instruction: string): string {
  switch (category) {
    case "generation": {
      // Extract the content type from the instruction
      const m = instruction.match(/\b(haiku|poem|rhyme|joke|quote|story|caption|bio|tweet|note|essay|song|rap|letter|limerick|pun)\b/i);
      return m ? `Generate ${m[1].toLowerCase()}` : "Generate content";
    }
    case "whatsapp": {
      // Try to extract recipient name
      const m = instruction.match(/\b(to|for)\s+([A-Z][a-z]+)/);
      return m ? `WhatsApp → ${m[2]}` : "Send WhatsApp";
    }
    case "discord": {
      const m = instruction.match(/\b(dnd|idle|online|invisible|do not disturb)\b/i);
      return m ? `Discord: ${m[1].toLowerCase()}` : "Discord";
    }
    case "email":
      return "Send email";
    case "apps": {
      const m = instruction.match(/\b(open|launch|start)\b\s+(.+)/i);
      return m ? `Open ${m[2].trim()}` : "Launch app";
    }
    default:
      return instruction.slice(0, 40);
  }
}

// ---- LLM helper ----

/** One-shot LLM call: resolves with the full response text. */
function callLLM(model: string, messages: ChatMessage[]): Promise<string> {
  return new Promise((resolve, reject) => {
    let text = "";
    let settled = false;

    api.onChatToken((t) => { text += t; }).then((unsubToken) => {
      api.onChatComplete(() => {
        unsubToken();
        if (!settled) { settled = true; resolve(text.trim()); }
      }).then((unsubComplete) => {
        api.sendChatMessage(model, messages).catch((e) => {
          unsubComplete();
          if (!settled) { settled = true; reject(e); }
        });
      }).catch(reject);
    }).catch(reject);
  });
}
