/**
 * taskPlanner.ts
 * LLM-based task decomposition.
 *
 * For complex multi-step requests, asks the LLM to break the task into
 * ordered steps (one per line: "category: instruction").
 * Each step then executes with minimal, focused context.
 *
 * ponytail: no graph, no state machine, no enumerated noun lists.
 * Just one small planning call + a simple line parser.
 */



export interface TaskStep {
  id: string;
  label: string;
  category: string;
  /** Natural language instruction for this step */
  prompt: string;
  status: "pending" | "running" | "done" | "error";
  result?: string;
}

export interface TaskPlan {
  originalRequest: string;
  steps: TaskStep[];
  /** Content generated by earlier steps, keyed by content type (haiku, quote, etc.) */
  generatedContent: Record<string, string>;
}

// ---- Planning prompt ----

// ---- Pre-filter ----
// Avoids the planning LLM call for obviously simple single-step requests.

const CONJUNCTIONS = /\b(and then|and also|then|also|after that|afterwards|and set|and send|and message|and email|and open|and launch|and save|and take|and add|once you have|once done)\b/i;
const ACTION_WORDS = /\b(write|create|generate|compose|message|send|set|email|open|launch|discord|whatsapp|take|save|add|put)\b/i;

/**
 * Quick heuristic: does this request look like it needs multiple steps?
 * Only returns true if there's a conjunction AND at least one action keyword.
 * Avoids the planning LLM call for obviously simple single-step requests.
 */
export function mightBeMultiStep(text: string): boolean {
  return CONJUNCTIONS.test(text) && ACTION_WORDS.test(text);
}

// ---- Main entry ----

let _n = 0;
const nextId = () => `s${++_n}`;

/**
 * Ask the LLM to decompose a multi-step request.
 * Returns null if the LLM says it's a single step.
 */
export async function decomposeTask(
  userRequest: string,
): Promise<TaskPlan | null> {
  try {
    const response = await fetch("http://127.0.0.1:4891/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "local",
        messages: [
          {
            role: "system",
            content: "You are a simple task planner. Break the user's multi-step request into a sequence of atomic actions.\nOutput exactly one action per line in the format:\ncategory: instruction\n\nAvailable categories:\n- generation (for writing poems, essays, jokes, etc.)\n- notes (for saving/adding notes)\n- whatsapp (for sending messages)\n- discord (for discord status/activity)\n- apps (for opening/closing apps)\n- email (for sending emails)\n\nRules:\n1. No intro, no outro, no markdown blocks. Just the lines.\n2. If the user asks to send to multiple people, make separate whatsapp actions for each person.\n3. Keep instructions clear and self-contained.\n4. If it's just one step, output a single line."
          },
          { role: "user", content: userRequest }
        ],
        temperature: 0.1,
        stream: false,
      }),
    });

    if (response.ok) {
      const data = await response.json();
      const rawReply = (data.choices?.[0]?.message?.content || "").trim();
      
      const lines = rawReply.split("\n").map((l: string) => l.trim()).filter(Boolean);
      
      const steps: TaskStep[] = [];
      for (const line of lines) {
        const m = line.match(/^([a-z]+):\s*(.+)$/i);
        if (m) {
          const category = m[1].toLowerCase();
          const prompt = m[2].trim();
          steps.push({
            id: nextId(),
            label: makeLabel(category, prompt),
            category,
            prompt,
            status: "pending",
          });
        }
      }
      
      if (steps.length > 1) {
        return { originalRequest: userRequest, steps, generatedContent: {} };
      } else if (steps.length === 1) {
        return null;
      }
    }
  } catch (err) {
    console.error("LLM planner failed, falling back to regex parser:", err);
  }

  // Fallback
  return parseDirectPlan(userRequest);
}

function parseDirectPlan(userRequest: string): TaskPlan | null {
  const text = userRequest.trim();
  const normalized = text.replace(/^User Request:\s*/i, "");
  
  // Split on strong separators or conjunctions that are followed by an action verb
  // e.g. "and open", "also set", ", then send"
  const chunks = normalized
    .split(/\b(?:and then|after that|afterwards|then|and finally|finally)\b|[;។]|\b(?:also|and)\b(?=\s+(?:open|launch|set|send|write|create|dm|post|message|turn|close|start|save|take|add|put)\b)|,\s*(?:also\s+|then\s+|and\s+)?(?=(?:open|launch|set|send|write|create|dm|post|message|turn|close|start|save|take|add|put)\b)/i)
    .map((s) => s.trim())
    .filter(Boolean);

  const steps: TaskStep[] = [];
  for (const chunk of chunks) {
    const category = inferDirectCategory(chunk);
    if (!category) continue;

    const prompts = category === "whatsapp"
      ? expandWhatsAppTargets(chunk)
      : [chunk];

    for (const prompt of prompts) {
      const cleaned = cleanupDirectPrompt(category, prompt);
      if (!cleaned) continue;
      steps.push({
        id: nextId(),
        label: makeLabel(category, cleaned),
        category,
        prompt: cleaned,
        status: "pending",
      });
    }
  }

  if (steps.length <= 1) return null;
  return { originalRequest: userRequest, steps, generatedContent: {} };
}

function inferDirectCategory(chunk: string): string | null {
  const text = chunk.toLowerCase();
  if (/\b(write|create|compose|generate|draft)\b/.test(text) && /\b(poem|haiku|story|joke|quote|song|letter|essay|caption|rap|limerick|pun)\b/.test(text)) {
    return "generation";
  }
  if (/\b(take|save|write|add|put)\b/.test(text) && /\b(note|notes)\b/.test(text)) {
    return "notes";
  }
  if (/\b(turn on|turn off|enable|disable|auto[- ]?reply)\b/.test(text)) {
    return "whatsapp";
  }
  if (/\b(dm|discord|<@!?\d+>|status|activity)\b/.test(text)) {
    return "discord";
  }
  if (/\b(open|launch|start|close|quit|exit)\b/.test(text) && /\b(chrome|notepad|calculator|discord|browser)\b/.test(text)) {
    return "apps";
  }
  if (/\b(send|message|text|whatsapp)\b/.test(text)) {
    return "whatsapp";
  }
  return null;
}

function expandWhatsAppTargets(chunk: string): string[] {
  const hasRecipientList = /\b(to|for)\s+.+\b(and|,)\b.+/i.test(chunk);
  if (!hasRecipientList) return [chunk];

  const m = chunk.match(/^(.*?\b(?:to|for)\s+)(.+)$/i);
  if (!m) return [chunk];

  const prefix = m[1];
  const targetText = m[2].trim();
  const targets = targetText
    .split(/\s*(?:,| and | & )\s*/i)
    .map((s) => s.trim())
    .filter(Boolean);

  if (targets.length <= 1) return [chunk];
  return targets.map((target) => `${prefix}${target}`);
}

function cleanupDirectPrompt(category: string, prompt: string): string {
  let cleaned = prompt.trim().replace(/\s+/g, " ");

  if (category === "generation") {
    cleaned = cleaned.replace(/^(first\s+)?(write|create|compose|generate|draft)\s+/i, "Write ");
    cleaned = cleaned.replace(/\b(a\s+brief\s+summary|a\s+summary|summary)\b.*$/i, "");
  }

  if (category === "whatsapp") {
    cleaned = cleaned.replace(/^send\s+(it|that poem|the poem)\s+/i, "Send the poem ");
    cleaned = cleaned.replace(/\s+on\s+whatsapp\s*$/i, " on WhatsApp");
  }

  if (category === "discord") {
    cleaned = cleaned.replace(/\bopen\s+discord\b/i, "Open Discord");
    cleaned = cleaned.replace(/\bset\s+my\s+status\b/i, "Set Discord status");
    cleaned = cleaned.replace(/\bturn on auto-?reply\b/i, "Turn on auto-reply");
  }

  if (category === "apps") {
    cleaned = cleaned.replace(/\band search for.*$/i, "");
    cleaned = cleaned.replace(/\band save a short note.*$/i, "");
  }

  return cleaned.trim();
}

function makeLabel(category: string, instruction: string): string {
  switch (category) {
    case "generation": {
      // Extract the content type from the instruction
      const m = instruction.match(/\b(haiku|poem|rhyme|joke|quote|story|caption|bio|tweet|note|essay|song|rap|letter|limerick|pun)\b/i);
      return m ? `Generate ${m[1].toLowerCase()}` : "Generate content";
    }
    case "whatsapp": {
      // Try to extract recipient name
      const m = instruction.match(/\b(to|for)\s+([A-Z][a-z]+)/);
      return m ? `WhatsApp → ${m[2]}` : "Send WhatsApp";
    }
    case "discord": {
      const m = instruction.match(/\b(dnd|idle|online|invisible|do not disturb)\b/i);
      return m ? `Discord: ${m[1].toLowerCase()}` : "Discord";
    }
    case "email":
      return "Send email";
    case "apps": {
      const m = instruction.match(/\b(open|launch|start)\b\s+(.+)/i);
      return m ? `Open ${m[2].trim()}` : "Launch app";
    }
    default:
      return instruction.slice(0, 40);
  }
}


