/**
 * taskPlanner.ts
 * LLM-based task decomposition.
 *
 * For complex multi-step requests, asks the LLM to break the task into
 * ordered steps (one per line: "category: instruction").
 * Each step then executes with minimal, focused context.
 *
 * ponytail: no graph, no state machine, no enumerated noun lists.
 * Just one small planning call + a simple line parser.
 */

import { api, AppConfig, ChatMessage } from "../../lib/api";

export interface TaskStep {
  id: string;
  label: string;
  category: string;
  /** Natural language instruction for this step */
  prompt: string;
  status: "pending" | "running" | "done" | "error";
  result?: string;
}

export interface TaskPlan {
  originalRequest: string;
  steps: TaskStep[];
  /** Content generated by earlier steps, keyed by content type (haiku, quote, etc.) */
  generatedContent: Record<string, string>;
}

// ---- Planning prompt ----

const PLANNING_SYSTEM = `Break the user's request into steps. Output ONE LINE per step:
CATEGORY: instruction

Categories:
- generation: write/create/compose/generate any content
- whatsapp: send a WhatsApp message to someone
- discord: set Discord status or activity
- email: send an email
- apps: open or launch an application

If a person is named and no email address is given, use whatsapp unless the user explicitly says email/mail.
Auto-reply requests belong to whatsapp.

If only one step is needed, output: SIMPLE

---
Example:
User: Write a haiku about rust and message it to John on WhatsApp. Then set Discord to dnd with activity Debugging.
generation: Write a haiku about how hard it is to write Rust code
whatsapp: Send the haiku to John on WhatsApp
discord: Set Discord status to dnd with activity Debugging
---
Example:
User: Open Chrome and also set my Discord status to idle.
apps: Open Chrome
discord: Set Discord status to idle
---
Example:
User: What time is it?
SIMPLE
---
Now output the steps for the user's request below. Only output step lines or SIMPLE, nothing else.`;

// ---- Pre-filter ----
// Avoids the planning LLM call for obviously simple single-step requests.

const CONJUNCTIONS = /\b(and then|and also|then|also|after that|afterwards|and set|and send|and message|and email|and open|and launch|once you have|once done)\b/i;
const ACTION_WORDS = /\b(write|create|generate|compose|message|send|set|email|open|launch|discord|whatsapp)\b/i;

/**
 * Quick heuristic: does this request look like it needs multiple steps?
 * Only returns true if there's a conjunction AND at least one action keyword.
 * Avoids planning LLM calls for simple queries.
 */
export function mightBeMultiStep(text: string): boolean {
  return CONJUNCTIONS.test(text) && ACTION_WORDS.test(text);
}

// ---- Main entry ----

let _n = 0;
const nextId = () => `s${++_n}`;

/**
 * Ask the LLM to decompose a multi-step request.
 * Returns null if the LLM says it's a single step.
 */
export async function decomposeTask(
  userRequest: string,
  config: AppConfig,
): Promise<TaskPlan | null> {
  const direct = parseDirectPlan(userRequest);
  if (direct) return direct;

  const messages: ChatMessage[] = [
    { role: "system", content: PLANNING_SYSTEM },
    { role: "user", content: userRequest },
  ];

  const response = await callLLM(config.selected_model, messages);
  return parsePlanResponse(response, userRequest);
}

// ---- Parsing ----

const CATEGORY_RE = /^(generation|whatsapp|discord|email|apps):\s*(.+)$/i;

function parsePlanResponse(response: string, originalRequest: string): TaskPlan | null {
  const steps: TaskStep[] = [];

  for (const raw of response.split("\n")) {
    const line = raw.trim();
    // Skip blank lines, SIMPLE, and example separators
    if (!line || /^SIMPLE\b/i.test(line) || /^[-=]{2,}/.test(line)) continue;
    const m = line.match(CATEGORY_RE);
    const instruction = m ? m[2].trim() : line;
    const category = m
      ? normalizeCategory(m[1].toLowerCase(), instruction, originalRequest)
      : inferCategory(instruction, originalRequest);
    if (!instruction) continue;
    if (!category) continue;

    for (const expanded of expandRecipientTargets(category, instruction)) {
      steps.push({
        id: nextId(),
        label: makeLabel(category, expanded),
        category,
        prompt: expanded,
        status: "pending",
      });
    }
  }

  function normalizeCategory(category: string, instruction: string, originalRequest: string): string {
    const text = `${instruction} ${originalRequest}`.toLowerCase();
    const hasEmailCue = /\b(email|e-mail|mail|smtp|subject|body)\b/.test(text) || /\S+@\S+/.test(text);
    const hasWhatsAppCue =
      /\b(whatsapp|message|msg|text|auto[- ]?reply)\b/.test(text) ||
      /\b(send|send the|send it|forward)\b/.test(text);
    const hasDiscordCue =
      /\b(discord|guild|channel|server|role|dm|<@!?\d+>|auto[- ]?reply)\b/.test(text);
    const hasContentCue = /\b(write|create|compose|generate|poem|haiku|story|joke|quote|song|letter|note|essay|caption|rap|limerick|pun)\b/.test(text);

    if (category === "email" && !hasEmailCue && hasWhatsAppCue) {
      return "whatsapp";
    }

    if (category === "discord" && /\bauto[- ]?reply\b/.test(text)) {
      return "whatsapp";
    }

    if (category === "generation" && hasWhatsAppCue && !hasContentCue) {
      return hasEmailCue ? "email" : "whatsapp";
    }

    if (category === "generation" && /\b(send|post|message|dm)\b/.test(text) && !hasContentCue) {
      return hasEmailCue ? "email" : "whatsapp";
    }

    if (category === "email" && !hasEmailCue && /\b(rahul|chirag|rajan|alice|bob|john|dave|frank|parth|charlie)\b/.test(text)) {
      return "whatsapp";
    }

    if (category === "discord" && !hasDiscordCue && hasWhatsAppCue && !hasEmailCue) {
      return "whatsapp";
    }

    return category;
  }

  function inferCategory(instruction: string, originalRequest: string): string | null {
    const text = `${instruction} ${originalRequest}`.toLowerCase();
    if (/\b(email|e-mail|smtp|subject|body)\b/.test(text) || /\S+@\S+/.test(text)) {
      return "email";
    }
    if (/\b(discord|guild|channel|server|role|dm|<@!?\d+>)\b/.test(text)) {
      return "discord";
    }
    if (/\b(whatsapp|message|msg|text|auto[- ]?reply)\b/.test(text)) {
      return "whatsapp";
    }
    if (/\b(write|create|compose|generate|poem|haiku|story|joke|quote|song|letter|note|essay|caption|rap|limerick|pun)\b/.test(text)) {
      return "generation";
    }
    if (/\b(open|launch|start|close|quit|exit|chrome|notepad|calculator|discord)\b/.test(text)) {
      return "apps";
    }
    return null;
  }

  function expandRecipientTargets(category: string, instruction: string): string[] {
    if (category !== "whatsapp" && category !== "email" && category !== "discord") {
      return [instruction];
    }

    const m = instruction.match(/^(.*?\b(?:to|for)\s+)(.+)$/i);
    if (!m) return [instruction];

    const prefix = m[1];
    const targetText = m[2].trim();
    const targets = targetText
      .split(/\s*(?:,| and | & )\s*/i)
      .map((s) => s.trim())
      .filter(Boolean);

    if (targets.length <= 1) return [instruction];

    return targets.map((target) => `${prefix}${target}`);
  }

  // Only decompose if we found 2 or more distinct steps
  if (steps.length <= 1) return null;

  return { originalRequest, steps, generatedContent: {} };
}

function parseDirectPlan(userRequest: string): TaskPlan | null {
  const text = userRequest.trim();
  const normalized = text.replace(/^User Request:\s*/i, "");
  const chunks = normalized
    .split(/\b(?:and then|after that|afterwards|then|and finally|finally)\b|[;។]/i)
    .map((s) => s.trim())
    .filter(Boolean);

  const steps: TaskStep[] = [];
  for (const chunk of chunks) {
    const category = inferDirectCategory(chunk);
    if (!category) continue;

    const prompts = category === "whatsapp"
      ? expandWhatsAppTargets(chunk)
      : [chunk];

    for (const prompt of prompts) {
      const cleaned = cleanupDirectPrompt(category, prompt);
      if (!cleaned) continue;
      steps.push({
        id: nextId(),
        label: makeLabel(category, cleaned),
        category,
        prompt: cleaned,
        status: "pending",
      });
    }
  }

  if (steps.length <= 1) return null;
  return { originalRequest: userRequest, steps, generatedContent: {} };
}

function inferDirectCategory(chunk: string): string | null {
  const text = chunk.toLowerCase();
  if (/\b(write|create|compose|generate|draft)\b/.test(text) && /\b(poem|haiku|story|joke|quote|song|letter|note|essay|caption|rap|limerick|pun)\b/.test(text)) {
    return "generation";
  }
  if (/\b(turn on|turn off|enable|disable|auto[- ]?reply)\b/.test(text)) {
    return "whatsapp";
  }
  if (/\b(dm|discord|<@!?\d+>|status|activity)\b/.test(text)) {
    return "discord";
  }
  if (/\b(open|launch|start|close|quit|exit)\b/.test(text) && /\b(chrome|notepad|calculator|discord|browser)\b/.test(text)) {
    return "apps";
  }
  if (/\b(send|message|text|whatsapp)\b/.test(text)) {
    return "whatsapp";
  }
  return null;
}

function expandWhatsAppTargets(chunk: string): string[] {
  const hasRecipientList = /\b(to|for)\s+.+\b(and|,)\b.+/i.test(chunk);
  if (!hasRecipientList) return [chunk];

  const m = chunk.match(/^(.*?\b(?:to|for)\s+)(.+)$/i);
  if (!m) return [chunk];

  const prefix = m[1];
  const targetText = m[2].trim();
  const targets = targetText
    .split(/\s*(?:,| and | & )\s*/i)
    .map((s) => s.trim())
    .filter(Boolean);

  if (targets.length <= 1) return [chunk];
  return targets.map((target) => `${prefix}${target}`);
}

function cleanupDirectPrompt(category: string, prompt: string): string {
  let cleaned = prompt.trim().replace(/\s+/g, " ");

  if (category === "generation") {
    cleaned = cleaned.replace(/^(first\s+)?(write|create|compose|generate|draft)\s+/i, "Write ");
    cleaned = cleaned.replace(/\b(a\s+brief\s+summary|a\s+summary|summary)\b.*$/i, "");
  }

  if (category === "whatsapp") {
    cleaned = cleaned.replace(/^send\s+(it|that poem|the poem)\s+/i, "Send the poem ");
    cleaned = cleaned.replace(/\s+on\s+whatsapp\s*$/i, " on WhatsApp");
  }

  if (category === "discord") {
    cleaned = cleaned.replace(/\bopen\s+discord\b/i, "Open Discord");
    cleaned = cleaned.replace(/\bset\s+my\s+status\b/i, "Set Discord status");
    cleaned = cleaned.replace(/\bturn on auto-?reply\b/i, "Turn on auto-reply");
  }

  if (category === "apps") {
    cleaned = cleaned.replace(/\band search for.*$/i, "");
    cleaned = cleaned.replace(/\band save a short note.*$/i, "");
  }

  return cleaned.trim();
}

function makeLabel(category: string, instruction: string): string {
  switch (category) {
    case "generation": {
      // Extract the content type from the instruction
      const m = instruction.match(/\b(haiku|poem|rhyme|joke|quote|story|caption|bio|tweet|note|essay|song|rap|letter|limerick|pun)\b/i);
      return m ? `Generate ${m[1].toLowerCase()}` : "Generate content";
    }
    case "whatsapp": {
      // Try to extract recipient name
      const m = instruction.match(/\b(to|for)\s+([A-Z][a-z]+)/);
      return m ? `WhatsApp → ${m[2]}` : "Send WhatsApp";
    }
    case "discord": {
      const m = instruction.match(/\b(dnd|idle|online|invisible|do not disturb)\b/i);
      return m ? `Discord: ${m[1].toLowerCase()}` : "Discord";
    }
    case "email":
      return "Send email";
    case "apps": {
      const m = instruction.match(/\b(open|launch|start)\b\s+(.+)/i);
      return m ? `Open ${m[2].trim()}` : "Launch app";
    }
    default:
      return instruction.slice(0, 40);
  }
}

// ---- LLM helper ----

/** One-shot LLM call: resolves with the full response text. */
function callLLM(model: string, messages: ChatMessage[]): Promise<string> {
  return new Promise((resolve, reject) => {
    let text = "";
    let settled = false;

    api.onChatToken((t) => { text += t; }).then((unsubToken) => {
      api.onChatComplete(() => {
        unsubToken();
        if (!settled) { settled = true; resolve(text.trim()); }
      }).then((unsubComplete) => {
        api.sendChatMessage(model, messages).catch((e) => {
          unsubComplete();
          if (!settled) { settled = true; reject(e); }
        });
      }).catch(reject);
    }).catch(reject);
  });
}
