pub mod automations;
pub mod email;
pub mod memory;
pub mod model;
pub mod projects;
pub mod skills;
pub mod system;
pub mod todos;
pub mod notes;

pub use automations::*;
pub use email::*;
pub use memory::*;
pub use model::*;
pub use projects::*;
pub use skills::*;
pub use system::*;
pub use todos::*;
pub use notes::*;
